version: "3"

services:
  app:
    image: ${DOCKER_REGISTRY}/nestjs-eb-multi-container-docker
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
    restart: always
    container_name: nestjs-eb-multi-container-docker
  redis:
    container_name: test-redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  mysql:
    image: mysql:5.7.29
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    restart: always